%This draws the 6 parts for fig A1.  It uses data that can be generated by running run_invasion under the "shaken" conditions, specifically:
%run_invasion(1,1)
%run_invasion(2,1)
%run_invasion(3,1)
%run_invasion(4,1)
%run_invasion(6,1)
%run_invasion(7,1)

close all
clc, clear
load('20190603_invade_shaken_tradeoff')

figA=figure();
plot(log(mean(res5)),mean(res2),'ko',[-.02 .1],[-.02 .1],'k--')

title('(a) Dispersal-susceptibility trade-off','interpreter','latex')
xlabel('Actual invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')
ylabel('Estimated invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')

set(gca,'fontsize', 12);

set(figA,'Units','Inches');
pos = get(figA,'Position');
set(figA,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
saveas(figA,'figA1a.pdf')

[mean(mean(res3(:,:,4))), mean(mean(res3(:,:,6)))]

%%%%%%%%%%%%%%%%%%%%%%%

load('20190603_invade_shaken_justPred')

figA=figure();
plot(log(mean(res5)),mean(res2),'ko',[-.02 .1],[-.02 .1],'k--')

title('(b) Differences in predation','interpreter','latex')
xlabel('Actual invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')
ylabel('Estimated invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')

set(gca,'fontsize', 12);

set(figA,'Units','Inches');
pos = get(figA,'Position');
set(figA,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
saveas(figA,'figA1b.pdf')


[mean(mean(res3(:,:,4))), mean(mean(res3(:,:,6)))]

%%%%%%%%%%%%%%%%%%%%%%%

load('20190603_invade_shaken_justDisp')

figA=figure();
plot(log(mean(res5)),mean(res2),'ko',[-.02 .1],[-.02 .1],'k--')

title('(c) Differences in dispersal','interpreter','latex')
xlabel('Actual invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')
ylabel('Estimated invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')

set(gca,'fontsize', 12);

set(figA,'Units','Inches');
pos = get(figA,'Position');
set(figA,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
saveas(figA,'figA1c.pdf')

[mean(mean(res3(:,:,4))), mean(mean(res3(:,:,6)))]

%%%%%%%%%%%%%%%%%%%%%%%

load('20190603_invade_shaken_rand')

figA=figure();
plot(log(mean(res5)),mean(res2),'ko',[-.02 .1],[-.02 .1],'k--')

title('(e) Different dispersal \& susceptibility 1','interpreter','latex')
xlabel('Actual invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')
ylabel('Estimated invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')

set(gca,'fontsize', 12);

set(figA,'Units','Inches');
pos = get(figA,'Position');
set(figA,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
saveas(figA,'figA1e.pdf')

[mean(mean(res3(:,:,4))), mean(mean(res3(:,:,6)))]

%%%%%%%%%%%%%%%%%%%%%%%

load('20190603_invade_shaken_justYield')

figA=figure();
plot(log(mean(res5)),mean(res2),'ko',[-.02 .1],[-.02 .1],'k--')

title('(d) Baseline with yield differences','interpreter','latex')
xlabel('Actual invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')
ylabel('Estimated invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')

set(gca,'fontsize', 12);

set(figA,'Units','Inches');
pos = get(figA,'Position');
set(figA,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
saveas(figA,'figA1d.pdf')

[mean(mean(res3(:,:,4))), mean(mean(res3(:,:,6)))]

%%%%%%%%%%%%%%%%%%%%%%%

load('20190603_invade_shaken_rand2')

figA=figure();
plot(log(mean(res5)),mean(res2),'ko',[-.02 .1],[-.02 .1],'k--')

title('(f) Different dispersal \& susceptibility 2','interpreter','latex')
xlabel('Actual invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')
ylabel('Estimated invader growth rate, $\tilde{\lambda}_i^\prime$','interpreter','latex')

set(gca,'fontsize', 12);

set(figA,'Units','Inches');
pos = get(figA,'Position');
set(figA,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
saveas(figA,'figA1f.pdf')

[mean(mean(res3(:,:,4))), mean(mean(res3(:,:,6)))]